### ISSUE TITLE
Is there an example of how to use real data to prediction?

### ISSUE THREAD

**Issue by waldstein1983** [ibm-research-tokyo/dybm#6]
Dear authors,
I see the examples use NoisySin to generate a sin data with noise. The data structure of the result might be defined by dybm.
My question is, if I want to use my own data to prediction. How can I generate the suitable format for training?
Thx.
wald

**Comment by Cortixadmin** [comment]
@waldstein1983 An example using Pandas with real data provided in the form of CSV or text files is possible and shown here https://github.com/ibm-research-tokyo/dybm/blob/master/src/benchmarks/CompareLSTMandDyBM.py

This example uses the Linear, Gaussian and Nonlinear DyBM models and compared with a standard LSTM model implemented in Keras. It should be straightforward to try other DyBM models feeding in similar data format.

**Comment by waldstein1983** [comment]
Sorry for reopen this issue.
There is a FileNotFoundError: [Errno 2] No such file or directory.
Can you please share the data file?

**Comment by Cortixadmin** [comment]
data is publicly available here - https://datamarket.com/data/set/22t4/#!ds=22t4&display=line
you can refer to this paper - https://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14350
The above data link is for an univariate data, but you can use the same setup for other multivariate datasets.
